import {createState,validateState,parseBackup,backup,progressFor,updateProgress,addSession,toggleFavorite,stats,recommendations,tutorialUrl} from './model.js';
import {openStore} from './db.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=createState(),data,store,query='',level='全部',practiceLesson='L01',writeChain=Promise.resolve(),installPrompt=null,registration=null,offlineReady=false,updateReady=false;
const channel='BroadcastChannel' in window?new BroadcastChannel('xianxu-personal'):null;
const icon=(name)=>({today:'☀',skills:'▤',practice:'♫',profile:'◎'}[name]||'↗');
const route=()=>location.hash.slice(1)||'today';
const link=(href,label,cls='')=>`<a href="${esc(href)}" class="${cls}" target="_blank" rel="noopener noreferrer">${label} <span aria-hidden="true">↗</span></a>`;
const find=id=>data.lessons.find(l=>l.id===id);
const tutorial=()=>data.tutorials.find(t=>t.id===state.settings.tutorial);
const title=id=>find(id)?.title||id;
const selected=(a,b)=>a===b?' selected':'';
const checked=b=>b?' checked':'';
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3500);}
function go(target){location.hash=target;}
async function change(mutator){
  writeChain=writeChain.catch(()=>{}).then(async()=>{
    const task=async()=>{const current=await store.read();const next=validateState(mutator(current));await store.write(next);state=next;channel?.postMessage('changed');render();};
    if(navigator.locks)await navigator.locks.request('xianxu-personal-write',task);else await task();
  });
  try{await writeChain;return true;}catch(e){toast(e.message);return false;}
}
function header(){const current=route().split('/')[0];return `<aside class="sidebar"><a class="logo" href="#today"><span class="logo-icon">♮</span><span>弦序<small>MY GUITAR JOURNEY</small></span></a><nav aria-label="主导航">${[['today','今日'],['skills','技能路线'],['practice','练习记录'],['profile','我的']].map(([id,label])=>`<a class="nav-item ${current===id?'active':''}" href="#${id}"><span aria-hidden="true">${icon(id)}</span>${label}</a>`).join('')}</nav><div class="side-bottom"><span class="dot"></span> 个人版 · 本机保存<p>留一点时间，<br>给你喜欢的声音。</p><a href="#help">手机安装与备份 ↗</a></div></aside><div class="main-wrap"><header class="topbar"><a href="#today" class="mobile-logo">弦序</a><span class="desktop-label">一人，一把吉他，一点进步。</span><div class="top-actions"><span class="connection ${navigator.onLine?'':'offline'}">${navigator.onLine?'本机学习空间':'离线使用中'}</span><a href="#resources">教程资源 ↗</a></div></header><main id="main" tabindex="-1">`;}
function footer(){return `</main><footer class="page-footer">慢一点，把每一个音弹清楚。</footer></div><nav class="bottom-nav" aria-label="手机导航">${[['today','今日'],['skills','技能'],['practice','练习'],['profile','我的']].map(([id,label])=>`<a href="#${id}" class="${route().split('/')[0]===id?'active':''}"><span aria-hidden="true">${icon(id)}</span>${label}</a>`).join('')}</nav>`;}
function intro(kicker,heading,description){return `<div class="page-heading"><span class="eyebrow">${kicker}</span><h1>${heading}</h1><p>${description}</p></div>`;}
function lessonRow(l,index){const p=progressFor(state,l.id);return `<a href="#lesson/${l.id}" class="lesson-row"><span class="lesson-number">${String(index??l.order).padStart(2,'0')}</span><div><strong>${esc(l.title)}</strong><small>${esc(l.moduleTitle)} · ${p.skill==='confident'?'自评稳定':p.skill==='review'?'需要复练':p.practiced?'练过了':'尚未练习'}</small></div><span class="row-arrow">›</span></a>`;}
function today(){const s=stats(state),t=tutorial(),rec=recommendations(state,data.lessons);const plan=({10:[1,2,2,3,1,1],15:[1,3,3,5,2,1],25:[2,5,5,8,4,1],40:[3,8,8,13,6,2]})[state.settings.dailyMinutes];return `${intro('A LITTLE, EVERY DAY','每次练习，<br class="mobile-break">都有方向。','先跟着一位老师学，再用技能卡把难点练清楚。')}
<div class="today-grid"><section class="hero"><div class="hero-copy"><span class="eyebrow">YOUR NEXT CHORD</span><h2>从一根弦，<br>到一首歌。</h2><p>${esc(t.shortTitle)} · 第 ${state.position.part} 节<br>上次看到 ${esc(state.position.time)}</p>${link(tutorialUrl(t,state.position),'继续看主教程','button gold')}<a href="#position" class="hero-edit">记录继续点 →</a></div><div class="guitar" aria-hidden="true"><div class="neck"></div><div class="guitar-body"><div class="hole"></div></div><div class="strings"></div><div class="bridge"></div></div><span class="hero-foot">视频在原平台打开 · 使用实际免费内容</span></section>
<section class="card daily"><span class="eyebrow">TODAY’S PRACTICE</span><h2>留一点时间给吉他</h2><div class="daily-count"><span>${s.today}</span> / ${state.settings.dailyMinutes}<small>分钟</small></div><div class="progress-track"><div style="width:${Math.min(100,s.today/state.settings.dailyMinutes*100)}%"></div></div><p>今天练过的时间，由你如实记下。</p><a href="#practice" class="button primary">记一次练习 <span>＋</span></a><div class="mini-stats"><span>${s.days} <small>练习天数</small></span><span>${s.confident} <small>自评稳定</small></span></div></section></div>
<div class="section-head"><h2>今天，练这几件事</h2><a href="#skills">全部 60 张技能卡 ↗</a></div><div class="recommendations">${rec.map((r,i)=>`<a href="#lesson/${r.lesson.id}" class="card recommendation"><span class="serif muted">0${i+1}</span><div><span class="tag ${r.kind==='复练'?'ochre':''}">${r.kind}</span><h3>${esc(r.lesson.title)}</h3><p>${esc(r.reason)}</p></div><span class="row-arrow">›</span></a>`).join('')}</div>
<section class="card plan"><div class="section-head"><div><span class="eyebrow">YOUR SMALL ROUTINE</span><h2>${state.settings.dailyMinutes} 分钟，也能有所收获</h2></div><a href="#profile">调整目标 ↗</a></div><div class="plan-steps">${['准备','复习','新知识','专项练习','音乐应用','记录'].map((label,i)=>`<div><span>0${i+1}</span><strong>${label}</strong><small>${plan[i]} 分钟</small></div>`).join('')}</div><p class="muted">时间可以调整。先练最需要解决的一个问题，不要求每天闯过一课。</p></section>`;}
function filtered(){const q=query.trim().toLowerCase();return data.lessons.filter(l=>(level==='全部'||l.level===level||level==='收藏'&&state.favorites.includes(l.id)||level==='复习'&&(progressFor(state,l.id).skill==='review'||progressFor(state,l.id).reviewAt>0&&progressFor(state,l.id).reviewAt<=Date.now()))&&(!q||`${l.title} ${l.moduleTitle} ${l.objectives.join(' ')}`.toLowerCase().includes(q)));}
function skillResults(){const lessons=filtered();if(!lessons.length)return '<div class="empty">没有匹配的技能卡。试试其他关键词，或换一个筛选条件。</div>';return `<p class="result-count">找到 ${lessons.length} 张技能卡</p>`+data.modules.map((m,i)=>{const list=lessons.filter(l=>l.module===i+1);return list.length?`<section class="module"><div class="module-title"><span class="serif">${String(i+1).padStart(2,'0')}</span><div><h2>${esc(m)}</h2><p>${list.length} 张技能卡 · ${list[0].level}</p></div></div><div class="card lesson-list">${list.map(l=>lessonRow(l)).join('')}</div></section>`:'';}).join('');}
function skills(){return `${intro('THE LEARNING PATH','有路可循，也有处可查。','按主教程原课序学习；这 12 个模块，帮你找到想复练的技能。')}<div class="search-box"><span aria-hidden="true">⌕</span><input id="search" type="search" value="${esc(query)}" placeholder="搜索和弦、节奏或练习内容" aria-label="搜索技能卡"></div><div class="filters" role="group" aria-label="筛选技能">${['全部','入门','基础','进阶','收藏','复习'].map(x=>`<button class="chip ${level===x?'active':''}" data-action="filter" data-value="${x}" aria-pressed="${level===x}">${x}</button>`).join('')}</div><div id="skill-results">${skillResults()}</div>`;}
function lessonPage(id){const l=find(id);if(!l)return `${intro('NOT FOUND','这张卡片不在这里。','回到技能路线继续查找。')}<a href="#skills" class="button primary">返回技能路线</a>`;const p=progressFor(state,id);return `<a class="back-link" href="#skills">← 技能路线</a><div class="lesson-title"><div>${intro(`${l.id} · ${l.level}`,esc(l.title),esc(l.moduleTitle))}</div><button class="favorite ${state.favorites.includes(id)?'active':''}" data-action="favorite" data-id="${id}" aria-label="${state.favorites.includes(id)?'取消收藏':'收藏这张卡'}">${state.favorites.includes(id)?'★':'☆'}</button></div><div class="callout">个人练习建议，可按自己的情况调整。具体动作跟随主教程教师示范，技能卡不代表教师认证。</div><div class="detail-grid"><div><section class="card"><span class="eyebrow">WHAT TO LEARN</span><h2>这次，专注什么</h2><ul class="clean-list">${l.objectives.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section><section class="card"><span class="eyebrow">HOW TO PRACTICE</span><h2>拆成几个小步骤</h2><ol class="steps">${l.steps.map(v=>`<li>${esc(v)}</li>`).join('')}</ol><p class="exercise">${esc(l.practice.instruction)}</p>${l.notation?`<div class="notation">${esc(l.notation)}</div>`:''}<p class="muted">${l.practice.bpm} BPM 为可调整的起点 · ${esc(l.practice.beatUnit)}为一拍<br>${l.practice.bars} 小节 / 轮 × ${l.practice.rounds} 轮；概念课按目标练习，不强求节拍。</p></section><section class="card"><h2>留意这些小细节</h2><ul class="clean-list">${l.mistakes.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section></div><div><section class="card"><span class="eyebrow">MY PROGRESS</span><h2>从看过，到练稳</h2><label class="check-row"><input type="checkbox" data-action="watched" data-id="${id}"${checked(p.watched)}>我看过相关教学</label><p class="muted">${p.practiced?'✓ 已记录实际练习':'记录一次练习后，再自评是否稳定。'}</p><div class="status-options"><button class="chip ${p.skill==='review'?'active':''}" data-action="skill" data-id="${id}" data-value="review">需要复练</button><button class="chip ${p.skill==='confident'?'active':''}" data-action="skill" data-id="${id}" data-value="confident" ${p.practiced?'':'disabled'}>自评稳定</button></div><button class="button primary full" data-action="practice" data-id="${id}">记一次本课练习 ＋</button></section><section class="card"><h2>自查参考</h2><ul class="clean-list">${l.criteria.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section><section class="card"><form id="note-form" data-id="${id}"><label for="lesson-note"><h2>留一句给下次</h2></label><textarea id="lesson-note" name="note" maxlength="1000" placeholder="比如：先降到 50 BPM，检查第二弦的杂音。">${esc(p.note)}</textarea><button type="submit" class="button secondary full">保存这张卡的笔记</button></form></section><a href="#resources" class="text-link">去主教程找示范 ↗</a></div></div>`;}
function practice(){const l=find(practiceLesson)||data.lessons[0];return `${intro('MAKE IT A HABIT','练过的，都留下来。','手动记录有效练习时间。暂停、休息和看视频的时间不用凑进去。')}<div class="detail-grid"><section class="card"><form id="practice-form"><label>本次练习<select name="lessonId">${data.lessons.map(x=>`<option value="${x.id}"${selected(l.id,x.id)}>${x.id} ${esc(x.title)}</option>`).join('')}</select></label><div class="form-grid"><label>实际练习时长 · 分钟<input name="minutes" type="number" min="1" max="240" step="1" value="5" required></label><label>稳定速度 · BPM<input name="bpm" type="number" min="0" max="240" step="1" value="60" required><small>不涉及节拍时填 0</small></label></div><fieldset><legend>刚才练得怎么样</legend><div class="feedback-options">${[['steady','节奏稳定'],['hesitation','转换停顿'],['noise','存在杂音'],['retry','需要再练']].map(([id,label],i)=>`<label><input type="radio" name="feedback" value="${id}" ${i===0?'checked':''}><span>${label}</span></label>`).join('')}</div></fieldset><label>一个问题，或一点进步<textarea name="note" maxlength="1000" placeholder="今天哪里更顺了？下次先解决什么？"></textarea></label><button class="button primary full" type="submit">保存这次练习 →</button><p class="form-hint">保存到当前设备。稳定反馈不会自动标记“掌握”。</p></form></section><aside><section class="card green-tint"><span class="eyebrow">A GENTLE REMINDER</span><h2>不用急着加速。</h2><p>先把难点取出来练，再放回完整段落。一次解决一个具体问题就很好。</p><div class="divider"></div><p>明显不适时停下来，休息和调整也是练习的一部分。</p></section><section class="card"><h2>还没决定练什么？</h2>${recommendations(state,data.lessons).map(r=>lessonRow(r.lesson)).join('')}</section></aside></div>`;}
function position(){return `${intro('PICK UP WHERE YOU LEFT OFF','下次，从这里继续。','手动记下教程的分集和时间；原平台可能忽略时间参数，以这里的记录为准。')}<section class="card narrow"><form id="position-form"><label>我在跟的主教程<select name="tutorial">${data.tutorials.map(t=>`<option value="${t.id}"${selected(t.id,state.settings.tutorial)}>${esc(t.shortTitle)}（${t.parts} 分集）</option>`).join('')}</select></label><div class="form-grid"><label>第几节 / 分 P<input name="part" type="number" min="1" max="${tutorial().parts}" step="1" value="${state.position.part}" required></label><label>继续时间 · 分:秒<input name="time" inputmode="text" pattern="[0-9]{1,3}:[0-5][0-9]" placeholder="03:20" value="${esc(state.position.time)}" required></label></div><label>下次提醒<textarea name="note" maxlength="1000" placeholder="比如：先看慢速示范，再练两轮。">${esc(state.position.note)}</textarea></label><button type="submit" class="button primary full">保存继续点</button></form></section>`;}
function resources(){return `${intro('ONE TEACHER, ONE PATH','找一位老师，踏实学下去。','先选一套能在你手机上免费观看的主教程，不需要同时学两套。')}<div class="resources-grid">${data.tutorials.map((t,i)=>`<article class="card resource"><span class="tag">${i===0?'主教程候选':'备用教程'}</span><h2>${esc(t.shortTitle)}</h2><p>${esc(t.description)}</p><div class="resource-meta"><span>${t.parts} 个分集</span><span>中文 · 原平台观看</span></div>${link(t.url,'打开合集','button primary')}<button data-action="choose-tutorial" data-id="${t.id}" class="button secondary">${t.id===state.settings.tutorial?'当前主教程':'设为我的主教程'}</button></article>`).join('')}</div><div class="callout">核查日期：${data.checkedAt}。已核对公开目录，未逐集完整播放。是否免费、能否缓存及手机可访问性，以原平台当前页面为准；遇到收费或无法访问的内容，改用免费替代资源。</div><section class="card"><h2>补充工具与支线</h2>${data.resources.map(r=>`<div class="resource-row"><div><strong>${esc(r.title)}</strong><p>${esc(r.use)}</p></div>${link(r.url,'前往','text-link')}</div>`).join('')}</section><p class="muted">这里只保存入口，不下载或重新上传第三方视频。离线观看视频请使用原平台允许的免费缓存功能。</p>`;}
function profile(){const s=stats(state);return `${intro('MY GUITAR JOURNEY','听见自己的进步。','不需要账号。你的收藏、笔记和练习记录保存在这台设备。')}<div class="stat-cards">${[[s.total,'累计练习分钟'],[s.days,'练习天数'],[s.confident,'自评稳定技能']].map(([n,label])=>`<div class="card"><span class="serif">${n}</span><p>${label}</p></div>`).join('')}</div><section class="card"><div class="section-head"><h2>每天的一小段时间</h2><span class="muted">随时调整，不设连续打卡压力</span></div><div class="filters">${[10,15,25,40].map(n=>`<button class="chip ${n===state.settings.dailyMinutes?'active':''}" data-action="goal" data-value="${n}" aria-pressed="${n===state.settings.dailyMinutes}">${n} 分钟</button>`).join('')}</div></section><div class="detail-grid"><section><div class="section-head"><h2>我的收藏</h2><a href="#skills">查看技能路线 ↗</a></div><div class="card lesson-list">${state.favorites.length?state.favorites.map(id=>lessonRow(find(id))).join(''):'<p class="empty">在技能卡点一下 ☆，把想练的内容留在这里。</p>'}</div><div class="section-head"><h2>练习足迹</h2><span class="muted">最近 30 次</span></div>${state.sessions.slice(0,30).map(r=>`<article class="card session"><div class="section-head"><a href="#lesson/${r.lessonId}"><h3>${esc(title(r.lessonId))}</h3></a><span class="tag">${({steady:'稳定',hesitation:'停顿',noise:'杂音',retry:'再练'})[r.feedback]}</span></div><p class="muted">${new Date(r.finishedAt).toLocaleDateString('zh-CN')} · ${r.minutes} 分钟${r.bpm?' · '+r.bpm+' BPM':''}</p>${r.note?`<p class="session-note">${esc(r.note)}</p>`:''}</article>`).join('')||'<div class="card empty">第一次练习，会从这里开始留下足迹。</div>'}</section><aside><section class="card backup-card"><span class="eyebrow">KEEP YOUR PROGRESS</span><h2>给进步留份备份</h2><p>本机数据不会自动跨设备同步。浏览器清理、卸载或换手机前，请导出备份。</p><button class="button primary full" data-action="export">导出我的学习备份 ↓</button><button class="button secondary full" data-action="import">导入已有备份 ↑</button><p class="muted">JSON 文件仅下载到你选择的位置，不上传到服务器。</p></section><section class="card"><h2>随时都能打开</h2><p>${offlineReady?'✓ 界面和 60 张技能卡已缓存，可离线打开。':'正在检查离线缓存；请联网等待缓存就绪后再离线。'}</p>${updateReady?'<button class="button secondary full" data-action="update">新版本就绪，立即更新</button>':''}<button class="button secondary full" data-action="install">添加到手机桌面</button><a class="text-link" href="#help">安装与使用说明 ↗</a></section></aside></div>`;}
function help(){return `${intro('TAKE IT WITH YOU','装进口袋，随时拿起。','个人版不需要微信 AppID、云数据库、云存储或付费订阅。')}<div class="detail-grid"><div><section class="card"><h2>Android 手机</h2><ol class="steps"><li>在 Chrome 等支持 PWA 的浏览器中打开正式 HTTPS 链接。</li><li>点击浏览器菜单里的“安装应用”或“添加到主屏幕”，也可点下方安装按钮。</li><li>等“我的”页面显示离线缓存就绪，再试着断网打开技能卡。</li></ol><button class="button primary" data-action="install">安装到桌面</button></section><section class="card"><h2>iPhone</h2><ol class="steps"><li>在 Safari 打开正式链接，不在微信内置浏览器里安装。</li><li>打开分享菜单，选择“添加到主屏幕”；如果提供“作为网页 App 打开”，将其启用。</li><li>添加后从桌面图标打开一次，检查离线状态与数据保存。</li></ol></section><section class="card"><h2>数据怎么保管</h2><p>记录只保存在当前浏览器 / 应用的 IndexedDB。不同设备、不同浏览器和不同网站域名之间不会自动共享。</p><p>定期在“我的”导出 JSON。新设备打开同一应用后导入；导入会替换当前数据，系统会先显示记录数量供你确认。</p><p>应用更新保留本机记录。普通网页缓存与学习数据库分开管理。浏览器可能清理站点数据，备份仍然必要。</p><button class="button secondary" data-action="export">现在导出备份</button></section></div><aside><section class="card green-tint"><h2>哪些能离线？</h2><ul class="clean-list"><li>界面、60 张技能卡、练习建议。</li><li>你的收藏、进度、笔记与练习记录。</li><li>原平台视频需要网络；本应用不会缓存视频。</li></ul><p class="muted">第一次打开必须联网，完成缓存后电脑可关机。</p></section><section class="card"><h2>费用与隐私</h2><p>应用不含收费功能、广告分析脚本、登录或远程数据接口。托管使用免费的静态页面服务；视频流量使用你现有的网络条件。</p><p>静态托管方会按其自身规则处理普通网站访问请求；点开视频后进入原平台。你的学习记录不会随访问上传。</p><p>本地开发地址不能当成手机永久入口，应使用正式 HTTPS 地址安装。</p></section></aside></div>`;}
function render(){const r=route();const page=r.startsWith('lesson/')?lessonPage(r.split('/')[1]):({today,skills,practice,profile,position,resources,help})[r]?.()||today();$('#app').innerHTML=header()+page+footer();document.title=(r.startsWith('lesson/')?title(r.split('/')[1])+' · ':'')+'弦序 · 个人版';}
async function confirmImport(incoming){const dialog=$('#confirm');$('#confirm-title').textContent='用这份备份恢复学习记录？';$('#confirm-body').textContent=`备份含 ${incoming.sessions.length} 次练习、${incoming.favorites.length} 个收藏。确认后将替换本机的 ${state.sessions.length} 次练习记录。建议先取消并导出当前记录，以便回退。`;return new Promise(resolve=>{dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true});dialog.showModal();});}
function download(){const blob=new Blob([backup(state)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`弦序学习备份-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('备份已生成，请确认保存在下载或文件 App 中。');}
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;$('#skill-results').innerHTML=skillResults();}});
document.addEventListener('change',async e=>{if(e.target.dataset.action==='watched'){const el=e.target;if(!await change(s=>updateProgress(s,el.dataset.id,{watched:el.checked})))el.checked=!el.checked;}if(e.target.name==='tutorial'){const form=e.target.form,t=data.tutorials.find(t=>t.id===e.target.value);form.elements.part.max=t.parts;form.elements.part.value='1';form.elements.time.value='00:00';}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const {action,id,value}=b.dataset;
  if(action==='filter'){level=value;render();}
  if(action==='favorite')await change(s=>toggleFavorite(s,id));
  if(action==='skill')await change(s=>updateProgress(s,id,{skill:value}));
  if(action==='practice'){practiceLesson=id;go('practice');}
  if(action==='goal')await change(s=>({...s,settings:{...s.settings,dailyMinutes:Number(value)},updatedAt:Date.now()}));
  if(action==='choose-tutorial'){if(id===state.settings.tutorial){go('position');return;}if(await change(s=>({...s,settings:{...s.settings,tutorial:id},position:{part:1,time:'00:00',note:''},updatedAt:Date.now()})))toast('已设为主教程，从第 1 节开始。');}
  if(action==='export')download();if(action==='import')$('#backup-file').click();
  if(action==='install'){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;}else{go('help');toast('请使用浏览器菜单中的“安装”或“添加到主屏幕”。');}}
  if(action==='update'){await writeChain.catch(()=>{});registration?.waiting?.postMessage({type:'ACTIVATE_UPDATE'});}
});
document.addEventListener('submit',async e=>{const form=e.target;if(!['practice-form','position-form','note-form'].includes(form.id))return;e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;const f=new FormData(form);let success=false;
  if(form.id==='practice-form'){const r={id:crypto.randomUUID(),lessonId:String(f.get('lessonId')),minutes:Number(f.get('minutes')),bpm:Number(f.get('bpm')),feedback:String(f.get('feedback')),note:String(f.get('note')),finishedAt:Date.now()};success=await change(s=>addSession(s,r));if(success){toast('练习已保存在这台设备。');go('profile');}}
  if(form.id==='position-form'){success=await change(s=>({...s,settings:{...s.settings,tutorial:String(f.get('tutorial'))},position:{part:Number(f.get('part')),time:String(f.get('time')),note:String(f.get('note'))},updatedAt:Date.now()}));if(success){toast('继续点已保存。');go('today');}}
  if(form.id==='note-form'){success=await change(s=>updateProgress(s,form.dataset.id,{note:String(f.get('note'))}));if(success)toast('笔记已保存。');}
  if(!success)button.disabled=false;
});
$('#backup-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>50*1024*1024)throw Error('备份文件超过 50 MB');const incoming=parseBackup(await file.text());if(await confirmImport(incoming)){if(await change(()=>({...incoming,updatedAt:Date.now()})))toast('学习记录已恢复到本机。');}}catch(error){toast(error.message);}finally{e.target.value='';}});
window.addEventListener('hashchange',()=>{render();scrollTo(0,0);});
function updateConnection(){const el=$('.connection');if(el){el.textContent=navigator.onLine?'本机学习空间':'离线使用中';el.classList.toggle('offline',!navigator.onLine);}}
window.addEventListener('online',()=>{updateConnection();toast('网络已连接，可打开原平台视频。');});window.addEventListener('offline',()=>{updateConnection();toast('已离线，本机学习记录仍可使用。');});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
channel?.addEventListener('message',async()=>{try{state=await store.read();if(!document.querySelector('#practice-form,#position-form,#note-form,input:focus,textarea:focus,select:focus'))render();}catch(e){toast(e.message);}});
async function setupOffline(){if(!('serviceWorker' in navigator))return;try{registration=await navigator.serviceWorker.register('./sw.js');const ready=await navigator.serviceWorker.ready;offlineReady=!!ready.active;updateReady=!!registration.waiting;if(route()==='profile')render();registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){updateReady=true;if(route()==='profile')render();toast('新版本已就绪，可在“我的”中更新。');}});});let reloaded=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(updateReady&&!reloaded){reloaded=true;location.reload();}});}catch{toast('离线缓存尚未就绪，请保持联网后重试。');}}
async function main(){try{const [content,db]=await Promise.all([fetch('./data.json').then(r=>{if(!r.ok)throw Error('课纲加载失败');return r.json();}),openStore()]);data=content;store=db;state=await store.read();render();void setupOffline();}catch(e){$('#app').innerHTML=`<main class="loading"><span class="wordmark">弦序</span><h1>暂时无法打开学习空间</h1><p>${esc(e.message)}</p><p>请确认已联网，且没有使用限制存储的隐私模式。</p><button class="button primary" onclick="location.reload()">重新打开</button></main>`;}}
void main();
